# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '7.0'
target 'Yelp' do

pod 'AFNetworking'
pod 'BDBOAuth1Manager' , '~> 1.2.0'

end

target 'YelpTests' do

end

